# Generated by Django 3.2.12 on 2022-10-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjtk2', '0004_add_id_autofield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('dba', 'DBA'), ('employee', 'Employee')], db_index=True, default='Employee', max_length=30),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='category',
            field=models.CharField(choices=[('Core', 'core'), ('Suggested', 'suggested'), ('Custom', 'custom')], default='Custom', max_length=30),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='scope',
            field=models.CharField(choices=[('FD', 'Fishery Dependent'), ('FI', 'Fishery Independent'), ('MS', 'Multiple Sources')], default='FI', max_length=30),
        ),
    ]
