# Generated by Django 3.2.12 on 2022-10-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjtk2', '0007_populate_projectimage_alt_text_from_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='alt_text',
            field=models.CharField(max_length=1000, verbose_name='alternative text for screen readers'),
        ),
    ]
